apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: matching-default
spec:
  role: KarpenterNodeRole-T3-Wagu-Matching-EKS

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: T3-Wagu-Matching-EKS

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: T3-Wagu-Matching-EKS

  tags:
    Name: T3-Wagu-Matching-Karpenter-Node
    Project: WAGUWAGU
