apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agones-sdk
  namespace: game
rules:
- apiGroups: ["agones.dev"]
  resources: ["gameservers"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk
  namespace: game
subjects:
- kind: ServiceAccount
  name: agones-sdk
  namespace: game
- kind: ServiceAccount
  name: game-server-sa
  namespace: game
roleRef:
  kind: Role
  name: agones-sdk
  apiGroup: rbac.authorization.k8s.io
