apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: waguwagu-autoscaler
  namespace: game
spec:
  fleetName: waguwagu-fleet
  policy:
    # 여유 서버를 5개 유지
    type: Buffer
    buffer:
      bufferSize: 5
      minReplicas: 5
      maxReplicas: 10
