apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: route53-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: T3-Wagu-Secrets
        property: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: route53-credentials-secret
  namespace: game
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: route53-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-access-key
      remoteRef:
        key: T3-Wagu-Secrets
        property: AWS_SECRET_ACCESS_KEY
