apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: game-default
spec:
  role: KarpenterNodeRole-T3-Wagu-Game-EKS

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: T3-Wagu-Game-EKS

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: T3-Wagu-Game-EKS

  tags:
    Name: T3-Wagu-Game-Karpenter-Node
    Project: WAGUWAGU
